name: PR Checks
on:
  push:
    branches:
      - master

jobs:
  commit-lint:
    if: false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-commit-lint
      cancel-in-progress: true
    name: Commitlint
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
  lint:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
    runs-on: ${{ matrix.runner }}
    name: Lint ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: |
          pnpm install -w
      - name: lint
        run: |
          pnpm lint:ci
      - name: syncpack
        run: pnpm sp lint
  build:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubicloud-standard-2
          - ubicloud-standard-4
          - ubicloud-standard-8
          - ubicloud-standard-16
          - ubicloud-standard-30
    runs-on: ${{ matrix.runner }}
    name: Build & Test ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install & Build
        run: pnpm install
      - name: Publint
        run: pnpm publint:all
      - name: Are The Types Wrong
        run: pnpm attw:all
      - name: Test
        run: pnpm test:all --skip-nx-cache

  tsdoc-check:
    if: false
    runs-on: ubuntu-latest
    name: Check TSDoc Links
    concurrency:
      group: ${{ github.ref }}-tsdoc-check
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Check TSDoc Links
        run: npx tsdoc-link-check --patterns packages/**
